Miss a 'None' in return values of create_model() in tools/train_net.py
Summary:
When 'model_final.pkl' exists, the following error occurs:
```shell
INFO train_net.py: 184: model_final.pkl exists; no need to train!
Traceback (most recent call last):
  File "tools/train_net.py", line 280, in <module>
    main()
  File "tools/train_net.py", line 119, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 128, in train_model
    model, weights_file, start_iter, checkpoints, output_dir = create_model()
ValueError: need more than 4 values to unpack
```
It misses a return value.
Closes https://github.com/facebookresearch/Detectron/pull/309

Reviewed By: ir413

Differential Revision: D7366733

Pulled By: rbgirshick

fbshipit-source-id: c37b3b2e5b2aff38d46ca521a9d79613049255cb